### ISSUE TITLE
Basic instructions

### ISSUE THREAD

**Issue by jt196** [GrubHubGitTub/r-television-Weekly-Thread-Data#2]
Assuming you've left this up here for other folks to run, would you be up for putting some basic instructions on how to use the script? 

- I need a dev account, right? Where do I enter the credentials? 
- Which script do I run? 
- How do I enter the URL of the weekly thread?
- Are there any CLI arguments?

**Comment by GrubHubGitTub** [comment]
Let me get a proper requirements and readme going.

**Comment by GrubHubGitTub** [comment]
Please check the new readme.

**Comment by jt196** [comment]
Awesome, good job!
